name: Selenium CI Pipeline

on:
  push:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v5

      - name: Set up Java
        uses: actions/setup-java@v5
        with:
          distribution: 'temurin'
          java-version: '21'

      - name: Build and Run Tests
        run: mvn clean test -Dheadless=true

      - name: Upload Extent Report
        uses: actions/upload-artifact@v4
        with:
            name: extent-report
            path: Reports/ndosiAutomationReport.html

      - name: Send Email with Extent Report
        uses: dawidd6/action-send-mail@v3
        with:
          server_address: smtp.gmail.com
          server_port: 587
          username: ${{ secrets.EMAIL_USERNAME }}
          password: ${{ secrets.EMAIL_PASSWORD }}
          subject: Automation Test Results - Extent Report
          to: mthalane_n@yahoo.com
          from: ${{ secrets.EMAIL_USERNAME }}
          body: Hi, please find attached the latest Extent Report.
          attachments: Reports/ndosiAutomationReport.html